CREATE TABLE JABATAN (
   ID  BIGSERIAL NOT NULL,
   NAMA VARCHAR(140),
   LEVEL INTEGER,
   PRIMARY KEY (ID)
);

CREATE TABLE PEGAWAI (
   ID  BIGSERIAL NOT NULL,
   NAMA VARCHAR(140),
   PRIMARY KEY (ID)
);